package com.application.parser.options;

import org.apache.beam.sdk.options.Description;
import org.apache.beam.sdk.options.PipelineOptions;
import org.apache.beam.sdk.options.Validation.Required;

public interface IngestionOptions extends PipelineOptions {

    @Description("Absolute path of the source data file to process")
    @Required
    String getFilePath();
    void setFilePath(String value);

    @Description("Unique Execution ID generated by the Spring Boot API")
    @Required
    String getExecutionId();
    void setExecutionId(String value);

    @Description("Input file type, for example JSON or CSV")
    @Required
    String getFileType();
    void setFileType(String value);

    @Description("PostgreSQL password")
    @Required
    String getDatabasePassword();
    void setDatabasePassword(String value);
}
